module.exports = [
    'Temel’s Tea and Cafe',
    'Dursun’s Eggziting Dishes',
    'Bebek Kazanı',
    'Aç Ceket',
    'Anne Ve Çocuk Kazanı',
    'Süslü Ceket',
    'Isır Beni!',
    'Pumpkins and Walnuts',
    'The Walnut Tree',
    'Hodjas Bilgeliği',
    'Akşehir Bilge Adam',
    'Sayısız Yıldız',
    'Dünyanın Merkezi',
    'Çeviride Kayıp',
    'Batman’s Cave',
    'Afiyet Olsun Bosver',
    'Ölü Kazan Yaşıyor',
    'Ceket Yemek',
    'Snacks and Ladders',
    'Eats Mediterranean',
    'It’s A-Meze-ng!',
    'The Turkish Tickler',
    'Taking Turkey',
    'Bob’s Kebabs',
    'Kebab VIP',
    'Ali’s Persian Kebab',
    'Mortal Kebab',
    'Jabbar Kebab House',
    'Kebabiliciuos',
    'Fun Kebabs',
    'Kebab Capital',
    'Kebab and the City',
    'Kebab Club',
    'Uncle Kebab’s House',
    'To Infinity and Kebab',
    'Türk Kebab and Doners',
    'Şehirdeki En İyi Kebap',
    'Şiş ve Daha Fazlası',
    'Bay ve Bayan Kebap',
    'Kebap Köşesi',
    'Kıtalararası Kebap ve Döner',
    'Muhteşem Kebap ve Döner Çocuklar',
    'Kebap Yeniden Tasarlandı',
    'Kebap ve Döner Uzmanları',
    'Mediterranean Twist',
    'Battal Shawarma Shop',
    'Adam’s Grill and Shisha House',
    'Hayri Mediterranean Cuisine',
    'Stan’s and Anatoly’s',
    'Kader Turkish Restaurant',
    'Persian Table',
    'Türk Kahvaltısı',
    'Çay Ve Menemen',
    'Ev Yapımı',
    'Pita Doner',
    'Yemek Masası',
    'Kahvaltı Menüsü',
    'Sanat Mutfağı',
    'Kebap Kasabası',
    'Süper Eriyik Peynir Restoranı',
    'Tamamen Dolu',
    'Tuzlu Ve Tatlı',
    'Eve Hoşgeldin',
    'Yemek Molası',
    'Türk Tarzı',
    'The Turkish Diner',
    'The Turkish Lunch',
]